version: '3.8'

services:
  app:
    env_file: ./.env
    restart: unless-stopped
    build: 
      context: .
      dockerfile: Dockerfile
   
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    
  db:
    env_file: ./.env
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - ./.db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_DATABASE}
    
    ports:
      - "${DB_PORT}:${DB_PORT}"

