# knex db configuration
---
token:
  expiresIn: 3600
  secret: "super secret"

database:
  client: postgres
  connection:
    host: "db"
    database: 'postgres'
    user: 'postgres'
    password: 'postgres'

strapi:
  graphql_endpoint: http://localhost:1337/graphql
