# knex db configuration
---
token:
  expiresIn: 180
  secret: "super secret"

database:
  client: postgres
  connection:
    database: 'finhub'
    user: 'postgres'
    password: '12345'

strapi:
  graphql_endpoint: http://localhost:1337/graphql
