
// marketstack
// no Moscow exchange prices
GET http://api.marketstack.com/v1/eod?access_key=a144b7d1a13a321bb86b7a871c6f0975&symbols=YNDX

###
GET  http://api.marketstack.com/v1/tickers/GAZP.MISX?access_key=a144b7d1a13a321bb86b7a871c6f0975


// eodhistoricaldata
// Good to go 
//  checked with tinkoff data = it's ok 

###
GET https://eodhistoricaldata.com/api/eod/GAZP.MCX?api_token=637fdf2ad211e8.85627921&fmt=json

###
GET https://eodhistoricaldata.com/api/search/GAZPROM?api_token=637fdf2ad211e8.85627921 

###
GET https://eodhistoricaldata.com/api/exchange-symbol-list/MCX?api_token=637fdf2ad211e8.85627921&fmt=json 

###
https://eodhistoricaldata.com/api/exchanges-list/?api_token=637fdf2ad211e8.85627921

###
GET https://eodhistoricaldata.com/api/exchange-symbol-list/MCX?api_token=637fdf2ad211e8.85627921 
